# Generated by Django 3.2.18 on 2023-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crane_images/'),
        ),
    ]
