# Generated by Django 3.2.18 on 2024-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='drivers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'staff_type': 'driver'}, related_name='work_as_driver', to='work_management.Staff'),
        ),
        migrations.AddField(
            model_name='work',
            name='helpers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'staff_type': 'helper'}, related_name='work_as_helper', to='work_management.Staff'),
        ),
    ]
